### ISSUE TITLE
Why bother with template directives?

### ISSUE THREAD

**Issue by cowwoc** [floodfx/undead#25]
Instead of trying to recreate a programming language using template directives, why not just use normal Java code to generate and return HTML code? This is what React Remix does and it's way easier to use and read.

**Comment by floodfx** [comment]
Hey there @cowwoc!

What "normal" java code generates and returns HTML?   Like a different template engine?  Undead uses [StringTemplate](https://github.com/floodfx/undead#templating) mostly because it is a templating engine that makes it easy to get the data structure we need.  Most other template engines don't provide access to the "raw" data structures behind the templates themselves - rather they just return the rendered string which isn't what we need.  

The template directives are completely optional so there is nothing stopping you from using embedded expressions in your StringTemplates.  

That said, StringTemplate-based HTML templates are so new that I think it is worth experimenting with tools that *might* make them easier to build.  I'd suggest you try them out more extensively and see what you think.  Maybe compare / contrast  some template examples?  

I don't understand your point re: React Remix.  Remix is a javascript-based framework which is a completely different language than Java with different package manager, build chain, etc.   The idea with Undead is you only need to write Java.  No javascript.  No FE vs BE, etc...

**Comment by floodfx** [comment]
Happy to continue convo but closing the issue.

**Comment by cowwoc** [comment]
Forgetting the programming platform for a second, Remix lets you build up an HTML document using Javascript code. Example: https://stackoverflow.com/q/77306709/14731 or `${cat}` in https://css-tricks.com/the-basics-of-remix/

You can literally build up the HTML script using the full power of Javascript or calculate values in JS and embed them using `${foo}`.

I have nothing against embedding simple values in code (e.g. `${foo}`). I'm just objecting to the idea of moving for-loops into the templating engine. I am advocating that operations of any kind should live outside of the content.
